### ISSUE TITLE
production checklist

### ISSUE THREAD

**Issue by jamesturk** [openstates/people#16]
- [x] remove /test/ directory from code & repo
- [x] make --incoming default for to_yaml & remove --reset option
- [x] add real data, do retirements & lint it
- [x] disable person/committee scrapers in openstates/openstates
- [x] import all data to new prod OCD db
- [x] automate imports

**Comment by jamesturk** [comment]
data is now generated for all 50 states(+DC/PR)
